// Generated by CoffeeScript 1.6.3
var query_results;

window.presentation = {
  Models: {},
  Collections: {},
  Views: {},
  Routers: {},
  init: function() {
    'use strict';
    return $('#query').spelling();
  }
};

$(function() {
  'use strict';
  return presentation.init();
});

query_results = function(ret) {};
