// Generated by CoffeeScript 1.6.3
window.presentation = {
  Models: {},
  Collections: {},
  Views: {},
  Routers: {},
  init: function() {
    'use strict';
    return console.log('Hello from Backbone!');
  }
};

$(function() {
  'use strict';
  return presentation.init();
});
